stages:
  - analyze
  - arch
  - dev
  - ext

variables:
  GCC_PEDANTIC: ''
  GCC_STRICT: '-Wall -Wextra -Werror -Wno-long-long -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable -Wno-nested-anon-types -Wno-gnu-zero-variadic-macro-arguments'
  GCC_C_FLAGS: '-O3 -DNDEBUG'

    # -----------------------------------------------------------------------------
    # Check SRCs
    # -----------------------------------------------------------------------------
sanity:
  image: alexshcdr/tekon-debian-x86-64
  stage: analyze
  script:

    - echo '1. Encoding'
    - find -name  '*.cpp' -o -name '*.h' -o -name 'CMakeLists.txt' | xargs file -is | grep  -E -v 'utf-8|us-ascii' && exit 1 || echo -e 'OK\n\n'

  tags:
    - docker

    # -----------------------------------------------------------------------------
    # AMD64
    # -----------------------------------------------------------------------------
x86-64:
  image: alexshcdr/tekon-debian-x86-64
  stage: arch
  script:
    - cmake . -DCMAKE_C_FLAGS="$GCC_C_FLAGS $GCC_STRICT $GCC_PEDANTIC"
    - make -j $NCPU
  artifacts:
    expire_in: 1 hour
    paths:
    - mb_driver_ext
  tags:
    - docker

    # -----------------------------------------------------------------------------
    # ARMv7
    # -----------------------------------------------------------------------------
armhf:
  stage: arch
  image: alexshcdr/tekon-debian-armhf
  script:
    - cmake .  -DCMAKE_TOOLCHAIN_FILE="targets/xscale-uc8410a.cmake" -DCMAKE_C_FLAGS="$GCC_C_FLAGS $GCC_STRICT $GCC_PEDANTIC"
    - make -j $NCPU
  artifacts:
    expire_in: 1 hour
    paths:
    - mb_driver_ext
  tags:
    - docker

    # -----------------------------------------------------------------------------
    # MOXA UC8410A ToolChain v2
    # -----------------------------------------------------------------------------
uc8410a-tcv2:
  stage: dev
  image: alexshcdr/mb_driver_ext_uc8410a_tcv2
  script:
    - cmake .  -DCMAKE_C_COMPILER=/usr/local/arm-linux-gnueabihf-4.9/usr/bin/arm-linux-gnueabihf-gcc  -DCMAKE_CXX_COMPILER=/usr/local/arm-linux-gnueabihf-4.9/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_C_FLAGS="-O3 -DNDEBUG -Wall -Wextra -Werror -Wno-long-long -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable"
    - make -j $NCPU
  artifacts:
    expire_in: 1 hour
    paths:
    - mb_driver_ext
  tags:
    - docker



    # -----------------------------------------------------------------------------
    # MOXA UC 7420 Plus
    # -----------------------------------------------------------------------------
uc7420-plus:
  stage: dev
  image: alexshcdr/mb_driver_ext_uc7420plus
  script:
    - cmake . -DCMAKE_C_COMPILER=/usr/local/xscale_be/bin/xscale_be-gcc  -DCMAKE_CXX_COMPILER=/usr/local/xscale_be/bin/xscale_be-g++ -DCMAKE_C_FLAGS="$GCC_C_FLAGS -DBIG_ENDIAN=1 -Wall -Wextra"
    - make -j $NCPU
  artifacts:
    expire_in: 1 hour
    paths:
    - mb_driver_ext
  tags:
    - docker

    # -----------------------------------------------------------------------------
    # MOXA UC 7112 Plus
    # -----------------------------------------------------------------------------
uc7112-plus:
  stage: dev
  image: alexshcdr/mb_driver_ext_uc7112plus
  script:
    - cmake . -DCMAKE_C_COMPILER=/usr/local/arm-linux/bin/arm-linux-gcc -DCMAKE_CXX_COMPILER=/usr/local/arm-linux/bin/arm-linux-g++ -DCMAKE_C_FLAGS="$GCC_C_FLAGS -Wall"
    - make -j $NCPU
  artifacts:
    expire_in: 1 hour
    paths:
    - mb_driver_ext
  tags:
    - docker

    # -----------------------------------------------------------------------------
    # Static analyzers
    # -----------------------------------------------------------------------------
cppcheck:
  image: alexshcdr/tekon-debian-analyze
  stage: ext
  script:
    # Подготовка
    - echo 'No errors' > report_linux.txt

    # CPPCHECK
    - cppcheck --enable=all  --verbose --quiet -I. .  2&>report_linux.txt

    # Вывод результатов
    - echo '1. Linux'
    - cat report_linux.txt

    # Анализ ошибок
    - grep -E 'error|portability|performance' report_linux.txt  && exit 1 || echo 'OK'
  artifacts:
    expire_in: 7 day
    when: always
    paths:
    - report_linux.txt
  tags:
    - docker
